// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfLbrn5d03oawSAv_tzOUCdVwT04RLe6w',
    appId: '1:397601090646:web:edab867262237630811ff7',
    messagingSenderId: '397601090646',
    projectId: 'buzzinga-b1ba2',
    authDomain: 'buzzinga-b1ba2.firebaseapp.com',
    storageBucket: 'buzzinga-b1ba2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRNAURHrxK60lIURwdy0VsQlvZHf61hwM',
    appId: '1:397601090646:android:1b336f831dec8308811ff7',
    messagingSenderId: '397601090646',
    projectId: 'buzzinga-b1ba2',
    storageBucket: 'buzzinga-b1ba2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHZDYFfNd0oZkz2zjmi7I-ARvnpEXHRAg',
    appId: '1:397601090646:ios:452559236b660e6b811ff7',
    messagingSenderId: '397601090646',
    projectId: 'buzzinga-b1ba2',
    storageBucket: 'buzzinga-b1ba2.appspot.com',
    iosBundleId: 'com.example.buzzinga',
  );
}
